# Generated by Django 4.0.5 on 2022-07-11 05:51

from django.db import migrations, models
import django.db.models.deletion
import judge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_rename_email_myuser_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_id', models.PositiveBigIntegerField(default=0)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Input_Format', models.TextField()),
                ('Output_Format', models.TextField()),
                ('Constraint', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input_File', models.FileField(upload_to=judge.models.TestCase.upload_file_name_input)),
                ('Output_file', models.FileField(upload_to=judge.models.TestCase.upload_file_name_output)),
                ('Problem_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submission_Time', models.DateTimeField(auto_now_add=True)),
                ('Language', models.CharField(max_length=10)),
                ('Code', models.FileField(upload_to=judge.models.Submission.upload_code_name)),
                ('Result', models.CharField(default='None', max_length=20)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.myuser')),
            ],
        ),
    ]
