# Generated by Django 4.0.5 on 2022-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='Input_File',
            field=models.FileField(upload_to='testfiles/input/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Output_file',
            field=models.FileField(upload_to='testfiles/output/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
