# Generated by Django 4.0.5 on 2022-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_submission_submissionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='id',
        ),
        migrations.AlterField(
            model_name='submission',
            name='SubmissionId',
            field=models.PositiveBigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
