# Generated by Django 4.0.5 on 2022-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_submission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='Submission_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
