# Generated by Django 4.0.5 on 2022-07-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='email',
            new_name='email_id',
        ),
    ]
